# Generated by Django 3.2.3 on 2023-08-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='clone_times',
            field=models.IntegerField(default=0),
        ),
    ]
