# Generated by Django 3.2.3 on 2023-08-30 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_clone_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('preview_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project', unique=True)),
            ],
            options={
                'db_table': 'preview',
            },
        ),
    ]
