# Generated by Django 3.2.3 on 2023-08-30 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preview',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
    ]
