# Generated by Django 3.2.3 on 2023-08-31 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_preview_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='forward_type',
            field=models.CharField(choices=[('none', 'none'), ('item', 'item'), ('combined', 'combined')], default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='message_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.message'),
        ),
    ]
