# Generated by Django 3.2.3 on 2023-08-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230831_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_nickname',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
