# Generated by Django 3.2.3 on 2023-08-31 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_user_nickname'),
        ('app', '0007_file'),
    ]

    operations = [
    ]
