# Generated by Django 3.2.3 on 2023-08-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_0006_alter_user_user_nickname_0007_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='real_name',
            field=models.CharField(default='', max_length=1023),
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(default='file', max_length=255),
        ),
    ]
