# Generated by Django 3.2.3 on 2023-09-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_at_at_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='at',
            name='at_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
