# Generated by Django 3.2.3 on 2023-09-02 21:40

import app.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_message_message_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_avatar',
            field=models.CharField(default='avatar/DEFAULT_CHAT_AVATAR.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_avatar',
            field=models.ImageField(default='avatar/DEFAULT_CHAT_AVATAR.jpg', max_length=255, upload_to=app.tools.random_avatar_path),
        ),
    ]
